### ISSUE TITLE
[Bug]: 更新2.0.0/2.0.1后歌曲收藏列表消失

### ISSUE THREAD

**Issue by BOZHENG001** [lyswhut/lx-music-desktop#1095]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

更新2.0.0/2.0.1后歌曲收藏列表保留。

### 实际行为

更新2.0.0/2.0.1后歌曲收藏列表消失，并且已尝试下方链接中所提供的解决方案。

https://github.com/lyswhut/lx-music-desktop/releases/tag/v2.0.1

### Lx Music 版本

2.0.1

### 最后正常的版本

1.22.3

### 操作系统版本

windows 10

**Comment by lyswhut** [comment]
删除了`lx.data.db`后重新启动仍然不行吗？

**Comment by BOZHENG001** [comment]
是的，已经尝试删除`lx.data.db`后并重启软件，但是仍然无法显示收藏列表。

**Comment by lyswhut** [comment]
那你再删除掉它，然后去到软件安装目录，打开命令行启动程序（`./lx-music-desktop.exe`）看看会输出什么日志

**Comment by BOZHENG001** [comment]
```
D:\Music\lx-music-desktop>./lx-music-desktop.exe
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by BOZHENG001** [comment]
```
D:\Music\lx-music-desktop>lx-music-desktop.exe

D:\Music\lx-music-desktop>
10:18:38.658 > App starting...
init
SqliteError: unable to open database file
    at new Database (D:\Music\lx-music-desktop\resources\app.asar\node_modules\better-sqlite3\lib\database.js:63:26)
    at Object.init (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:236:14)
    at callback (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:361:48)
    at MessagePort.l (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:593:21)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'SQLITE_CANTOPEN'
}
db inited
10:18:38.922 > SqliteError: NOT NULL constraint failed: my_list_music_info.name
    at D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1387:38
    at sqliteTransaction (D:\Music\lx-music-desktop\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at overwriteListData (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1394:7)
    at Object.listDataOverwrite (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1736:5)
    at callback (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:361:48)
    at MessagePort.l (D:\Music\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:593:21)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
10:18:39.475 > Checking for update
10:18:39.476 > Checking for update...
10:18:40.655 > Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).
10:18:40.656 > Update not available.
```

**Comment by lyswhut** [comment]
你这是列表文件数据有问题，导致迁移失败了，跟我之前遇到的问题不一样，你这个情况应该只是列表数据丢失，启动后可以正常播放、收藏新的歌曲吧？方便压缩下`LxDatas`上层目录的那个`playList.json`发我邮箱`lyswhuit#qq.com`（#替换成@）看看吗？

**Comment by lyswhut** [comment]
@BOZHENG001 邮箱拼错了，卧槽

**Comment by BOZHENG001** [comment]
刚刚测试了一下，是可以正常播放和收藏新的歌曲的。

哈哈哈，没事，邮件还没发出去，刚把`playList.json`压缩了，这就给发过去。这里先提前感谢作者的帮助啊，哈哈

**Comment by lyswhut** [comment]
更新到v2.0.2，再次删除`lx.data.db`启动软件试试

**Comment by BOZHENG001** [comment]
已测试，列表已恢复，感激不尽！ From: lyswhutSent: Monday, 2 January 2023 11:19 amTo: lyswhut/lx-music-desktopCc: BOZHENG001; MentionSubject: Re: [lyswhut/lx-music-desktop] [Bug]: 更新2.0.0/2.0.1后歌曲收藏列表消失 (Issue #1095) 更新到v2.0.2，再次删除lx.data.db启动软件试试—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
