### ISSUE TITLE
[Bug]: Ubuntu 22.04 ARM64 2.0及以上版本的应用能安装但无法打开

### ISSUE THREAD

**Issue by Winnie0408** [lyswhut/lx-music-desktop#1105]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

2.0及以上版本应用能正常打开运行

### 实际行为

应用未能运行
尝试在终端中启动，报错如下：
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
11:35:47.561 ? App starting...
[28859:0104/113547.742671:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[28859:0104/113547.744474:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
init
Error: /tmp/.org.chromium.Chromium.YcDTsC: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:236:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled Rejection at: Promise  Promise {
  <rejected> Error: /tmp/.org.chromium.Chromium.YcDTsC: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
      at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
      at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
      at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
      at Module.load (node:internal/modules/cjs/loader:988:32)
      at Module._load (node:internal/modules/cjs/loader:829:12)
      at c._load (node:electron/js2c/asar_bundle:5:13343)
      at Module.require (node:internal/modules/cjs/loader:1012:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
      at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
}
 reason:  Error: /tmp/.org.chromium.Chromium.YcDTsC: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
11:35:48.218 ? Error: /tmp/.org.chromium.Chromium.YcDTsC: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
(node:28859) UnhandledPromiseRejectionWarning: Error: /tmp/.org.chromium.Chromium.YcDTsC: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
(Use `lx-music-desktop --trace-warnings ...` to show where the warning was created)
(node:28859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

### Lx Music 版本

2.0.2

### 最后正常的版本

1.22.3

### 操作系统版本

Ubuntu 22.04 LTS

### 附加信息

设备：小米平板5 Pro 5G
SoC：骁龙870
使用Termux在chroot容器中运行Ubuntu

**Comment by lyswhut** [comment]
由于重复<https://github.com/lyswhut/lx-music-desktop/issues/1102>，我现在关闭这个
