### ISSUE TITLE
[Bug]: 无法启动软件的BUG

### ISSUE THREAD

**Issue by fos236** [lyswhut/lx-music-desktop#1161]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

可以正常启动并使用软件

### 实际行为

实测[lx-music-desktop-v2.0.5-arm64.deb]在arm笔记本（笔记本型号擎云L410，操作系统UOS专业版(1024)，cpu  kirin990）安装以后无法启动，更换回[lx-music-desktop v1.22.3 arm64.deb]可以正常使用

### Lx Music 版本

2.0.5

### 最后正常的版本

1.22.3

### 操作系统版本

Linux PC 4.19.71-arm64-desktop #1 SMP PREEMPT Thu Jul 15 14:18:15 CST 2021 aarch64 GNU/Linux

**Comment by lyswhut** [comment]
在命令行启动程序，看看输出的日志

**Comment by fos236** [comment]
命令行试了一下，原来是新版软件的交叉编译器使用的版本太新了，[汗]，我的系统glibc库版本：
liu@liu-PC:~/temp$ strings /lib/aarch64-linux-gnu/libc.so.6 |grep GLIBC_
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_PRIVATE
命令行启动：
liu@liu-PC:/opt/lx-music-desktop$ ./lx-music-desktop 
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
10:33:38.533 › App starting...
[21285:0131/103338.555256:ERROR:browser_main_loop.cc(271)] GLib-GObject: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
init
Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.nuJbWs)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:236:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled Rejection at: Promise  Promise {
  <rejected> Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.nuJbWs)
      at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
      at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
      at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
      at Module.load (node:internal/modules/cjs/loader:988:32)
      at Module._load (node:internal/modules/cjs/loader:829:12)
      at c._load (node:electron/js2c/asar_bundle:5:13343)
      at Module.require (node:internal/modules/cjs/loader:1012:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
      at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
}
 reason:  Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.nuJbWs)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
10:33:39.054 › Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.nuJbWs)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
(node:21285) UnhandledPromiseRejectionWarning: Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.nuJbWs)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:244:14)
(Use `lx-music-desktop --trace-warnings ...` to show where the warning was created)
(node:21285) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by lyswhut** [comment]
你可以升级这个包吗

**Comment by fos236** [comment]
我尝试了编译安装glibc-2.29，编译成功，但是安装失败，缺少依赖，咨询了统信官方工程师，工程师查询了一下他们的私有仓库和共有仓库，仓库里最高版本到2.28，无法支持到2.29，没办法了，只能用1.22.3了

**Comment by lyswhut** [comment]
已经将GLIBC降级到了2.27，可以试试测试版是否可以运行：<https://github.com/lyswhut/lx-music-desktop/actions>

**Comment by fos236** [comment]
perfect！安装了测试版，可以启动软件正常使用了，谢谢！

**Comment by lyswhut** [comment]
已在v2.1.0修复
