### ISSUE TITLE
[Bug]: lx-music-desktop-v2.2.1-x64.AppImage 无法运行

### ISSUE THREAD

**Issue by SamLukeYes** [lyswhut/lx-music-desktop#1359]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

AppImage 应正常运行。在 NixOS 上，尽管不能直接运行 AppImage，但用 `appimage-run` 也应该能正常运行。

### 实际行为

```console
$ nix run 'nixpkgs#appimage-run' -- lx-music-desktop-v2.2.1-x64.AppImage
Uncompress lx-music-desktop-v2.2.1-x64.AppImage of type 02 @ offset 188392
[=============================================================-] 2171/2171 100%
lx-music-desktop-v2.2.1-x64.AppImage is now installed in /home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f
19:46:31.219 › App starting...
init
Error: /tmp/.org.chromium.Chromium.THh9TK: wrong ELF class: ELFCLASS32
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/dist/dbService.worker.js:380:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled Rejection at: Promise  Promise {
  <rejected> Error: /tmp/.org.chromium.Chromium.THh9TK: wrong ELF class: ELFCLASS32
      at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
      at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
      at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
      at Module.load (node:internal/modules/cjs/loader:1011:32)
      at Module._load (node:internal/modules/cjs/loader:846:12)
      at f._load (node:electron/js2c/asar_bundle:2:13330)
      at Module.require (node:internal/modules/cjs/loader:1035:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at new Database (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
      at Object.init (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/dist/dbService.worker.js:388:14)
}
 reason:  Error: /tmp/.org.chromium.Chromium.THh9TK: wrong ELF class: ELFCLASS32
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/dist/dbService.worker.js:388:14)
19:46:32.084 › Error: /tmp/.org.chromium.Chromium.THh9TK: wrong ELF class: ELFCLASS32
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/home/yes/.cache/appimage-run/68c0c63ac5b04ed69422b611ced44e8efc73cf8cf8f2d2a3d1e714734fba760f/resources/app.asar/dist/dbService.worker.js:388:14)
```

### Lx Music 版本

2.2.1

### 最后正常的版本

2.2.0

### 操作系统版本

Linux absolute 6.1.26 #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr 26 12:28:44 UTC 2023 x86_64 GNU/Linux

### 附加信息

对报错信息中提示 wrong ELF class 的文件进行检查，发现它并不是 x86-64 架构的 ELF 文件。

```console
$ nix run 'nixpkgs#file' -- /tmp/.org.chromium.Chromium.THh9TK
/tmp/.org.chromium.Chromium.THh9TK: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=a824bb1b746a7a8106e59dcaff14487402f78fa3, stripped
```

测试用的系统添加了 qemu-user-static 的 binfmt，因此可以运行其他架构的 ELF，不知道这会不会是该问题的触发条件。

**Comment by SamLukeYes** [comment]
2.2.2 似乎没问题了
