### ISSUE TITLE
[Bug]: linux x64版本无法打开软件

### ISSUE THREAD

**Issue by yjb152-yjb** [lyswhut/lx-music-desktop#1365]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常打开

### 实际行为

点打开没反应

### Lx Music 版本

2.2.2

### 最后正常的版本

2.2.1

### 操作系统版本

ubuntu18.04

**Comment by mingyuezhaowo** [comment]
遇到了同样的问题，log 如下：
xxx@~ $ lx-music-desktop &
[1] 31773
xxx@~ $ Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
15:55:05.709 › App starting...
init
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.94Z5G1)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:380:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled Rejection at: Promise  Promise {
  <rejected> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.94Z5G1)
      at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
      at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
      at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
      at Module.load (node:internal/modules/cjs/loader:1011:32)
      at Module._load (node:internal/modules/cjs/loader:846:12)
      at f._load (node:electron/js2c/asar_bundle:2:13330)
      at Module.require (node:internal/modules/cjs/loader:1035:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
      at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:388:14)
}
 reason:  Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.94Z5G1)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:388:14)
15:55:06.167 › Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.94Z5G1)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:388:14)

**Comment by lyswhut** [comment]
系统的glibc版本太低导致的，现在要求GLIBC_2.28才能使用，详情看这里：<https://github.com/WiseLibs/better-sqlite3/issues/990>，你可以尝试自己构建安装包：
注释掉以下行<https://github.com/lyswhut/lx-music-desktop/blob/ea5e8b56dde4acf25d4a383eeeaa8b6fdae7b4f3/build-config/build-before-pack.js#L59>
执行`npm run build && npm run pack:linux:deb:x64`构建
