### ISSUE TITLE
[Bug]: Ubuntu 18.04 安装之后，启动时报错

### ISSUE THREAD

**Issue by sdsafsdfsaf** [lyswhut/lx-music-desktop#1465]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装之后，希望执行成功

### 实际行为

启动时错误信息如下：
``` Bash
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
14:24:49.809 › App starting...
init
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.79ShLM)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:380:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled Rejection at: Promise  Promise {
  <rejected> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.79ShLM)
      at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
      at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
      at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
      at Module.load (node:internal/modules/cjs/loader:1011:32)
      at Module._load (node:internal/modules/cjs/loader:846:12)
      at f._load (node:electron/js2c/asar_bundle:2:13330)
      at Module.require (node:internal/modules/cjs/loader:1035:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
      at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:388:14)
}
 reason:  Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.79ShLM)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:388:14)
14:24:50.372 › Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.79ShLM)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:50:11)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:388:14)

```

### Lx Music 版本

2.3.0

### 操作系统版本

Ubuntu 18.04

**Comment by lyswhut** [comment]
Linux版本过低，当前版本不再支持 Ubuntu 18，你可以尝试安装v2.2.0及之前的版本，或者通过源码编译安装包
