### ISSUE TITLE
[Bug]: SqliteError: unable to open database file 和 table "dislike_list" already exists

### ISSUE THREAD

**Issue by dhtantoy** [lyswhut/lx-music-desktop#1567]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装成功后第一次可以正常启动，关闭后就无法打开。

### 实际行为

第一次启动的日志
`Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
14:29:23.464 › App starting...
init
SqliteError: unable to open database file
    at new Database (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/database.js:69:26)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:443:14)
    at callback (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:574:48)
    at MessagePort.l (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:806:21)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'SQLITE_CANTOPEN'
}
db inited`

第二次启动的日志
`Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
14:29:29.381 › App starting...
init
Unhandled Rejection at: Promise  Promise {
  <rejected> Error [SqliteError]: table "dislike_list" already exists
      at Database.exec (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
      at migrateV1 (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:409:8)
      at migrate (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:419:13)
      at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:459:9)
      at callback (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:574:48)
      at MessagePort.l (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:806:21)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
      at exports.emitMessage (node:internal/per_context/messageport:23:28)
}
 reason:  Error [SqliteError]: table "dislike_list" already exists
    at Database.exec (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at migrateV1 (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:409:8)
    at migrate (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:419:13)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:459:9)
    at callback (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:574:48)
    at MessagePort.l (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:806:21)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
14:29:29.938 › SqliteError: table "dislike_list" already exists
    at Database.exec (/opt/lx-music-desktop/resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at migrateV1 (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:409:8)
    at migrate (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:419:13)
    at Object.init (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:459:9)
    at callback (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:574:48)
    at MessagePort.l (/opt/lx-music-desktop/resources/app.asar/dist/dbService.worker.js:806:21)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)`

### Lx Music 版本

2.4.0

### 最后正常的版本

2.3.0

### 操作系统版本

Linux 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux

**Comment by lyswhut** [comment]
更新到2.4.1
