### ISSUE TITLE
[Bug]: 深色模式切换异常

### ISSUE THREAD

**Issue by yours57** [lyswhut/lx-music-desktop#1697]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

如题，主题的自动切换异常，不会随着系统自动切换浅、深色主题，除非完整退出应用然后重新打开。

查看log发现有如下报错，不知是否有关
[2023-11-17 10:53:33.254] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:53:33.269] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:53:33.281] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:55:07.033] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:55:55.274] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:55:55.278] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:56:09.086] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:56:09.190] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:56:09.207] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)
[2023-11-17 10:56:11.118] [error] TypeError: Cannot read properties of undefined (reading 'shouldUseDarkColors')
    at NativeTheme.<anonymous> (D:\Tools\lx-music\resources\app.asar\dist\main.js:49696:60)
    at NativeTheme.emit (node:events:513:28)

### 实际行为

跟随系统自动切换主题

### Lx Music 版本

2.5.0

### 最后正常的版本

2.4.0

### 操作系统版本

win 23H2

**Comment by lyswhut** [comment]
v2.5.0没动这块功能的代码，应该是更新到新版electron的系统主题颜色切换事件参数变更导致的，下个版本修复

**Comment by lyswhut** [comment]
已在v2.6.0修复
