### ISSUE TITLE
win11 上安装后不能正常显示页面，任务管理器中有记录，报错： <rejected> Error [TypeError]: Cannot read properties of undefined (reading 'field_value')

### ISSUE THREAD

**Issue by Tmaof** [lyswhut/lx-music-desktop#1843]
安装完成软件后点击启动，无法正常显示页面，使用命令行打开软件时，报错如下：
```
E:\lx-music-desktop>lx-music-desktop

E:\lx-music-desktop>
13:58:33.222 > App starting...
init
Unhandled Rejection at: Promise  Promise {
  <rejected> Error [TypeError]: Cannot read properties of undefined (reading 'field_value')
      at E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:24418
      at Object.init (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:24713)
      at n (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:5537)
      at MessagePort.i (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:25320)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
      at exports.emitMessage (node:internal/per_context/messageport:23:28)
}
 reason:  Error [TypeError]: Cannot read properties of undefined (reading 'field_value')
    at E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:24418
    at Object.init (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:24713)
    at n (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:5537)
    at MessagePort.i (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:25320)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
13:58:33.339 > TypeError: Cannot read properties of undefined (reading 'field_value')
    at E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:24418
    at Object.init (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:24713)
    at n (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:5537)
    at MessagePort.i (E:\lx-music-desktop\resources\app.asar\dist\dbService.worker.js:1:25320)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```
任务管理器有记录：
![image](https://github.com/lyswhut/lx-music-desktop/assets/102353901/f375a174-ae1d-4676-9605-bdacd363ffd9)

**Comment by lyswhut** [comment]
你在这之前做了什么操作？数据异常了，任务管理器结束掉残进程，在资源管理器地址栏输入 `%APPDATA%/lx-music-desktop/LxDatas`  回车，备份一下 `lx.data.db` 并删掉它，再启动程序应该就行了，但这会导致你的歌单数据丢失
如果上面的操作导致你的歌单数据丢失了，可以将原来的 `lx.data.db` 发到我邮箱看看能不能恢复
