### ISSUE TITLE
排行榜不能加载

### ISSUE THREAD

**Issue by 19162808632** [lyswhut/lx-music-desktop#383]
然后音乐的排行榜只能加载一次，如果去点击下一页就会出现白屏。并且这个时候任何音乐的排行榜都不能使用。

出现步骤：
1. 打开排行榜
2.选择下一页
3.无任何内容显示

目前可以通过退出软件，然后重新进入。可以正常加载排行榜，如果又重复上面的步骤，依旧会出现bug

**Comment by lyswhut** [comment]
什么源？请提供问题相关的截图

**Comment by 19162808632** [comment]
![无标题1](https://user-images.githubusercontent.com/60834637/102002772-d1ab6400-3d3a-11eb-9b74-de122c04a8d6.png)

**Comment by lyswhut** [comment]
歌单、搜索正常吗？

**Comment by 19162808632** [comment]
可以

**Comment by 19162808632** [comment]
目前就发现排行榜不能翻页

**Comment by lyswhut** [comment]
关掉软件，去`%HOMEPATH%\AppData\Roaming\lx-music-desktop`把`config.json`文件剪切走再启动软件试试

**Comment by 19162808632** [comment]
依然不能翻页
![Uploading 无标题1.png…]()

**Comment by lyswhut** [comment]
那你看下`%HOMEPATH%\AppData\Roaming\lx-music-desktop\logs`下有没有叫`renderer.log`的文件，有的话看下里面的日志并贴出来，没有的话你加下企鹅群@我

**Comment by 19162808632** [comment]
[2020-12-07 14:40:51.761] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-08 10:19:58.819] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-08 17:59:34.736] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-08 17:59:48.599] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-08 18:06:25.160] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-08 19:11:21.834] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-08 21:19:06.827] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-12 14:03:19.139] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-12 14:03:45.937] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255
[2020-12-12 14:05:27.908] [error] TypeError: Cannot read property 'getAttribute' of null
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421252)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at a (file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421341)
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:421385
    at file:///C:/Program%20Files/lx-music-desktop/resources/app.asar/dist/electron/renderer.js:2:12255

**Comment by lyswhut** [comment]
就这有这种错误码？

**Comment by 19162808632** [comment]
就是全部内容了

**Comment by lyswhut** [comment]
你加群`830125506`讨论吧
